[package]
name = "stfugame"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.45"
dotenvy = "0.15.7"
fastrand = "2.5.0"
serde_json = "1.0.151"
sf-api = "0.4.4"
tao = "0.37.1"
tokio = { version = "1.53.2", features = ["full"] }
tray-icon = "0.26.0"
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_System_Threading", "Win32_Security"] }
wry = "0.57.0"
